const writerFactory = require('../cjs/index').default;
const writerCliFactory = require('../cjs/index').cli;
const fs = require('fs');
const path = require('path');
const rimraf = require('rimraf');

const generatedFileContents = 'Generated by @static-pages/file-writer test runner. This file can be deleted safely.';
const renderer = d => d.output.body;
const buildDir = path.join(__dirname, 'build');

afterEach(() => {
	rimraf.sync('tests/build');
});

test('it writes a simple data object to file #1', async () => {
	const writer = writerFactory({
		outDir: buildDir,
	});

	await writer({
		header: {
			path: 'path/to/file.txt',
		},
		output: {
			body: generatedFileContents,
		},
	});

	const outputExists = fs.existsSync(path.join(buildDir, 'path/to/file.html'));

	expect(outputExists).toStrictEqual(true);
});

test('it writes a simple data object to file #2', async () => {
	const writer = writerFactory({
		outDir: buildDir,
		renderer,
	});

	await writer({
		output: {
			path: 'path/to/file.txt',
			body: generatedFileContents,
		},
	});

	const outputExists = fs.existsSync(path.join(buildDir, 'path/to/file.txt'));

	expect(outputExists).toStrictEqual(true);
});

test('it writes a simple data object to file #3', async () => {
	const writer = writerFactory({
		outDir: buildDir,
		renderer,
	});

	await writer({
		output: {
			url: 'path/to/file',
			body: generatedFileContents,
		},
	});

	const outputExists = fs.existsSync(path.join(buildDir, 'path/to/file.html'));

	expect(outputExists).toStrictEqual(true);
});

test('works with custom outFile()', async () => {
	const writer = writerFactory({
		outDir: buildDir,
		outFile(x) {
			return x.name;
		},
		renderer,
	});

	await writer({
		name: 'path/to/file.html',
		output: {
			body: generatedFileContents,
		},
	});

	const outputExists = fs.existsSync(path.join(buildDir, 'path/to/file.html'));

	expect(outputExists).toStrictEqual(true);
});

test('works with params from cli with arrow functions', async () => {
	const writer = writerCliFactory({
		outDir: buildDir,
		outFile: 'd => d.myPath',
		renderer: 'd => d.myOutput',
	});

	await writer({
		myPath: 'path/to/file.html',
		myOutput: generatedFileContents,
	});

	const outputExists = fs.existsSync(path.join(buildDir, 'path/to/file.html'));

	expect(outputExists).toStrictEqual(true);
});
